### ISSUE TITLE
Polynote fails with NoClassDefFoundError

### ISSUE THREAD

**Issue by dantodor** [polynote/polynote#1081]
**Description**
Trying to run Polynote with latest Spark distribution, it fails when trying to run spark.createDataFrame

1. Installed spark 3
2. installed Polynote and jep
3. Run polynote
4. Try to create a dataframe, language Scala

**Environment**
Ubuntu 18

java -version
openjdk version "11.0.10" 2021-01-19
OpenJDK Runtime Environment (build 11.0.10+9-Ubuntu-0ubuntu1.18.04)
OpenJDK 64-Bit Server VM (build 11.0.10+9-Ubuntu-0ubuntu1.18.04, mixed mode, sharing)

Spark 3

Polynote latest, no change in configuration.

**Logs**
 Exception in thread "main" java.lang.NoClassDefFoundError: scala/Function1$class
        |   	at zio.internal.tracing.ZIOFn1.<init>(ZIOFn.scala:35)
        |   	at zio.ZIO$MapFn.<init>(ZIO.scala:3377)
        |   	at zio.ZIO$class.map(ZIO.scala:801)
        |   	at zio.ZIO$Descriptor.map(ZIO.scala:3526)
        |   	at zio.ZIO$.<init>(ZIO.scala:2305)
        |   	at zio.ZIO$.<clinit>(ZIO.scala)
        |   	at zio.ZManaged$.<init>(ZManaged.scala:1316)
        |   	at zio.ZManaged$.<clinit>(ZManaged.scala)
        |   	at zio.ZLayer$.requires(ZLayer.scala:1999)

**Comment by jeremyrsmith** [comment]
This is probably due to mismatching Scala versions between Spark and Polynote. Spark 3 is (by default) built for Scala 2.12, so you'd need the matching Scala 2.12 distribution of Polynote.

Our next release (forthcoming!) gives a better solution to this, by packaging both Scala 2.11 and 2.12 versions in the same distribution.
