### ISSUE TITLE
`FreshRunReq` the second time a Python cell is run

### ISSUE THREAD

**Issue by indig** [polynote/polynote#51]
In a notebook, the second time a Python cell is run we get the following error:

```
Exception in thread "pool-3-thread-1" java.lang.Error: scala.tools.nsc.interactive.FreshRunReq
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1148)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:748)
Caused by: scala.tools.nsc.interactive.FreshRunReq
```

I believe this is due to https://github.com/polynote/polynote/blob/master/polynote-kernel/src/main/scala/polynote/kernel/lang/python/PythonInterpreter.scala#L150-L152

Unfortunately, our unit tests don't catch this because they generate a new global for each run rather than reusing it. 

If you comment out those lines, you run into
```
type String in scala.Predef not found
scala.ScalaReflectionException: type String in scala.Predef not found
	at scala.reflect.internal.ReificationSupport$ReificationSupportImpl.select(ReificationSupport.scala:25)
	at scala.reflect.internal.ReificationSupport$ReificationSupportImpl.selectType(ReificationSupport.scala:13)
	at scala.reflect.internal.ReificationSupport$ReificationSupportImpl.selectType(ReificationSupport.scala:11)
	at polynote.kernel.lang.python.PythonInterpreter$$typecreator1$1.apply(PythonInterpreter.scala:224)
```

**Comment by indig** [comment]
I'll leave the issue open as a reminder to handle this issue in a cleaner way than #52
