### ISSUE TITLE
Cannot run program "python3": error=2, No such file or directory

### ISSUE THREAD

**Issue by b-l-a-c-k-b-e-a-r-d** [polynote/polynote#615]
Polynote works as expected when I only use PySpark code.  I can load parquet files, run `groupBy`s, `show()` data, etc.  

When I have cells that mix Python and PySpark, I am seeing an error.  I first noticed this with a UDF.  Then again when trying to create an example to reproduce and post a simple notebook showing the issue.  The following code reliably reproduces the issue for me:

```
from pyspark.sql.types import IntegerType

my_list = [1, 2, 3, 4]
my_df   = pysparksession.createDataFrame(my_list, IntegerType())

my_df.show()
```

```
19/11/02 02:10:18 WARN TaskSetManager: Lost task 0.0 in stage 6.0 (TID 24, <server_name_removed>, executor 3): java.io.IOException: Cannot run program "python3": error=2, No such file or directory
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1048)
	at org.apache.spark.api.python.PythonWorkerFactory.startDaemon(PythonWorkerFactory.scala:173)
	at org.apache.spark.api.python.PythonWorkerFactory.createThroughDaemon(PythonWorkerFactory.scala:99)
	at org.apache.spark.api.python.PythonWorkerFactory.create(PythonWorkerFactory.scala:73)
	at org.apache.spark.SparkEnv.createPythonWorker(SparkEnv.scala:117)
	at org.apache.spark.api.python.BasePythonRunner.compute(PythonRunner.scala:86)
	at org.apache.spark.api.python.PythonRDD.compute(PythonRDD.scala:67)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:324)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:288)
	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:49)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:324)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:288)
	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:49)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:324)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:288)
	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:49)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:324)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:288)
	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:49)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:324)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:288)
	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:49)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:324)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:288)
	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:49)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:324)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:288)
	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:49)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:324)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:288)
	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:87)
	at org.apache.spark.scheduler.Task.run(Task.scala:109)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:345)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.io.IOException: error=2, No such file or directory
	at java.lang.UNIXProcess.forkAndExec(Native Method)
	at java.lang.UNIXProcess.<init>(UNIXProcess.java:248)
	at java.lang.ProcessImpl.start(ProcessImpl.java:134)
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1029)
	... 35 more

19/11/02 02:10:18 ERROR TaskSetManager: Task 0 in stage 6.0 failed 4 times; aborting job
```

I have set `PYSPARK_PYTHON` and `PYSPARK_DRIVER_PYTHON` as environment vars before starting polynote as well as defined those values in the ntoebook's Spark Config (e.g. `spark.yarn.appMasterEnv.PYSPARK_PYTHON`).

Any ideas?

**Comment by jonathanindig** [comment]
Hmm, I guess you are using a remote yarn master? I bet the python executable on the executor nodes is probably just `python` rather than `python3`. 

I don't have a lot of experience with pyspark or yarn, but if Polynote is supposed to use `python3` but your executors need `python`, I think you want to set something like `PYSPARK_DRIVER_PYTHON=python3` and `PYSPARK_PYTHON=python` (or the equivalent for yarn)

**Comment by b-l-a-c-k-b-e-a-r-d** [comment]
Hi Jonathan, 

I am running with a remote yarn master and have those variables set.  

> I have set `PYSPARK_PYTHON` and `PYSPARK_DRIVER_PYTHON` as environment vars before starting polynote as well as defined those values in the ntoebook's Spark Config (e.g. `spark.yarn.appMasterEnv.PYSPARK_PYTHON`).

I have the same setup for Jupyter and PySpark which work and leads me to think there is something going on in the way the spark job is being setup such that the environment is not being passed in.

**Comment by jonathanindig** [comment]
Hmm, we do set `PYSPARK_PYTHON` in the environment on our end which is probably why the environment variable method isn't working: https://github.com/polynote/polynote/blob/master/polynote-spark/src/main/scala/polynote/kernel/interpreter/python/PySparkInterpreter.scala#L64

I think a simple fix would just be to only set that variable if it's unset but that should probably be tested out first. 

In the meantime, I wonder whether setting the Spark config directly would override the environment-variable-based settings? 

Can you try setting `spark.pyspark.driver.python` to `python3` and `spark.pyspark.python` to `python` in the notebook's Spark config? Maybe that will override the environment we set.

**Comment by b-l-a-c-k-b-e-a-r-d** [comment]
The same error shows so it appears the the environment variable being set in polynote is taking precedence.

**Comment by b-l-a-c-k-b-e-a-r-d** [comment]
I found how to build polynote in gitter which helped me test this.  I can confirm that commenting out the else statement in the code reference @jonathanindig posted does allow my settings to take effect.  I am now hitting an issue where there are other environment variables that need to be set.  Once I work this out, I will submit a PR.

Thank you for your help!

**Comment by aaditkamat** [comment]
@b-l-a-c-k-b-e-a-r-d, are you still working on this issue?

**Comment by b-l-a-c-k-b-e-a-r-d** [comment]
It may be a week or two before I can get back to this.  Feel free to submit a PR if you can get to it sooner.

**Comment by jonathanindig** [comment]
I believe this might have been fixed by #743, so if anyone's still running into this problem, try setting `spark.pyspark.python` and `spark.pyspark.driver.python` to the correct executable for your system. 

Feel free to reopen this issue if you try that and it doesn't work. Thanks!

**Comment by gk24015** [comment]
I faced the same issue while using spark in pycharm. I took these steps and corrected it. 
Go to main.py---> Edit Configuration -->
![image](https://user-images.githubusercontent.com/48963206/120235080-eba01b00-c276-11eb-8f11-d9f630a0f422.png)
then go to environment variables and set path for PYSPARK_PYTHON 
![image](https://user-images.githubusercontent.com/48963206/120235341-69642680-c277-11eb-89b1-ce5cb3f3c1a7.png)

**Comment by truongthinh1412** [comment]
I'm encountering the same issue, here is the code to reproduce :
`from pyspark.sql import SparkSession

# create a Spark session
spark = SparkSession \
    .builder \
    .appName("Spark test") \
    .config("spark.pyspark.python","python") \
    .config("spark.pyspark.driver.python","python") \
    .getOrCreate()
from pyspark.sql.types import IntegerType

my_list = [1, 2, 3, 4]
my_df   = spark.createDataFrame(my_list, IntegerType())

my_df.show()`
