### ISSUE TITLE
Scala and Spark: java.lang.NoClassDefFoundError:

### ISSUE THREAD

**Issue by barana91** [polynote/polynote#636]
Hi, i wanted to try out polynote with Spark on Kubernetes but i'm running in an error.
I tried it also with the example Notebook with Spark in local mode but the same error appeared. 
I thought it could be a problem related to the scala version, because Spark 2.4.4 uses Scala version 2.11 and Polynote version 2.12 ?

Exception in thread "main" java.lang.BootstrapMethodError: java.lang.NoClassDefFoundError: scala/runtime/java8/JFunction0$mcZ$sp

´I'm using Spark 2.4.4 and i'm able to start the spark-shell and use it for computations. 
 (scala version 2.11.12 (OpenJDK 64-Bit Server VM, Java 1.8.0_222) 

**Reproduction**
Run the example Notebook -> Scala Spark to Pandas

**Environment**
spark-shell prints out 
Using Scala version 2.11.12 (OpenJDK 64-Bit Server VM, Java 1.8.0_222)
- Polynote Version: 
  - 0.2.12
- Operating System: 
  Ubuntu 18.04
- JVM Version:
 - 1.8.0_222
- Python Version:
 - Python 3.6.8
- How you installed Polynote: 
 -I installed Polynote on my local machine by following [these instructions](https://polynote.org/docs/01-installation.html).
- The command you are using to start Polynote:
   `./polynote.py`

**Notebook**
it happens when i'm using the /examples/Scala Spark to Pandas.ipynb Notebook

**Logs**

 spark-submit --class polynote.kernel.remote.RemoteKernelClient --driver-java-options "-Dlog4j.configuration=log4j.properties -Djava.library.path=/home/bavinc/.local/lib/python3.6/site-packages/jep" --driver-memory 2g --jars file:/home/bavinc/polynote/deps/polynote-spark-runtime.jar,file:/home/bavinc/polynote/deps/polynote-runtime.jar --conf spark.master=local[*] --conf spark.executor.userClasspathFirst=true --conf spark.driver.userClasspathFirst=true /home/bavinc/polynote/polynote.jar --address 10.10.XXX.XXX --port 41027 --kernelFactory polynote.kernel.LocalSparkKernelFactory
19/11/07 11:48:33 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
Exception in thread "main" java.lang.BootstrapMethodError: java.lang.NoClassDefFoundError: scala/runtime/java8/JFunction0$mcZ$sp
        at zio.scheduler.internal$$anon$1.<init>(SchedulerLive.scala:32)
        at zio.scheduler.internal$.<init>(SchedulerLive.scala:27)
        at zio.scheduler.internal$.<clinit>(SchedulerLive.scala)
        at zio.scheduler.SchedulerLive$$anon$3.<init>(SchedulerLive.scala:70)
        at zio.scheduler.SchedulerLive.$init$(SchedulerLive.scala:69)
        at polynote.app.App$$anon$1.<init>(App.scala:19)
        at polynote.app.App.$init$(App.scala:19)
        at polynote.kernel.remote.RemoteKernelClient$.<init>(RemoteKernel.scala:256)
        at polynote.kernel.remote.RemoteKernelClient$.<clinit>(RemoteKernel.scala)
        at polynote.kernel.remote.RemoteKernelClient.main(RemoteKernel.scala)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.apache.spark.deploy.JavaMainApplication.start(SparkApplication.scala:52)
        at org.apache.spark.deploy.SparkSubmit.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:845)
        at org.apache.spark.deploy.SparkSubmit.doRunMain$1(SparkSubmit.scala:161)
        at org.apache.spark.deploy.SparkSubmit.submit(SparkSubmit.scala:184)
        at org.apache.spark.deploy.SparkSubmit.doSubmit(SparkSubmit.scala:86)
        at org.apache.spark.deploy.SparkSubmit$$anon$2.doSubmit(SparkSubmit.scala:920)
        at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:929)
        at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
Caused by: java.lang.NoClassDefFoundError: scala/runtime/java8/JFunction0$mcZ$sp
        ... 22 more
Caused by: java.lang.ClassNotFoundException: scala.runtime.java8.JFunction0$mcZ$sp
        at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        ... 22 more

**Comment by jeremyrsmith** [comment]
Welcome! Thanks for the report!

I think this is probably a Scala version issue. If you're using Scala 2.12, you need to download the `polynote-dist-2.12.tar.gz` instead – we cross-build for both 2.11 and 2.12, but the 2.11 package is the default one.

Can you try again with the other tar? To be clear, we haven't tested the 2.12 build extensively ourselves, so if your Scala versions line up and you're still seeing problems, we'd love some further reports.

**Comment by barana91** [comment]
Hi Jeremy, 

i downloaded the release 0.2.11 (https://github.com/polynote/polynote/releases/download/0.2.11/polynote-dist.tar.gz) and tried it again and now everything works just fine.

**Comment by jeremyrsmith** [comment]
Glad to hear it!
