### ISSUE TITLE
Can't load CSV in polynote, but it works in jupyter lab and pyspark console

### ISSUE THREAD

**Issue by gosha1128** [polynote/polynote#647]
**Description** 

I try to load a CSV file and it fails.  The same exact code works in jupyter lab and pyspark console on the same machine.

**Reproduction**

>>from pyspark.sql import SparkSession
>>spark = SparkSession.builder.appName("My App").getOrCreate()
>>print(spark)
>>df = spark.read.csv("/Users/george/Projects/ApacheSparkWorkshop/test.csv",header=False,sep=",")
>>print(df)
>>df.collect()

This fails at "df.collect()".  Here is part of the stack trace:

Uncaught exception: Py4JJavaError: An error occurred while calling o39.collectToPython. : org.apache.spark.SparkException: Job aborted due to stage failure: Task 0 in stage 1.0 failed 1 times, most recent failure: Lost task 0.0 in stage 1.0 (TID 1, localhost, executor driver): java.lang.ClassCastException: cannot assign instance of org.apache.commons.lang3.time.FastDateFormat to field org.apache.spark.sql.execution.datasources.csv.CSVOptions.dateFormat of type org.apache.commons.lang3.time.FastDateFormat in instance of org.apache.spark.sql.execution.datasources.csv.CSVOptions at java.io.ObjectStreamClass$FieldReflector.setObjFieldValues(ObjectStreamClass.java:2287) at java.io.ObjectStreamClass.setObjFieldValues(ObjectStreamClass.java:1417) at java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:2293) at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:2211) at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2069) at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1573) at java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:2287) at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:2211) at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2069) at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1573) at java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:2287) at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:2211) at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2069) at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1573) at java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:2287) at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:2211) at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2069) at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1573) at java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:2287) at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:2211) at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2069) at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1573) at java.io.ObjectInputStream.readObject(ObjectInputStream.java:431) at scala.collection.immutable.List$SerializationProxy.readObject(List.scala:490) at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) at

**Environment**
I'm not using docker.  I download and extracted via the tar.gz.

- Polynote Version: 
  version is 0.2.8-SNAPSHOT.

- Operating System: 
Mac OS Sierra 10.12.6

- JVM Version:
java version "1.8.0_221"
Java(TM) SE Runtime Environment (build 1.8.0_221-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.221-b11, mixed mode)

- Python Version:
Python 3.7.1 (default, Dec 14 2018, 13:28:58) 
[Clang 4.0.1 (tags/RELEASE_401/final)] :: Anaconda custom (64-bit) on darwin

- How you installed Polynote: 
I downloaded and extracted the tar.gz, version is 0.2.8-SNAPSHOT.

- The command you are using to start Polynote:
  - `./polynote`

**Configuration**

**Notebook**

**Logs**

**Screenshots**

<img width="1680" alt="Screen Shot 2019-11-09 at 5 28 57 PM" src="https://user-images.githubusercontent.com/442121/68537330-8abc9500-0316-11ea-9cdd-054dd6649318.png">

**Additional context**

**Comment by jonathanindig** [comment]
@gosha1128 can you try again with the latest version (0.2.13)? Also, polynote creates a spark session for you, so there’s a `spark` variable already present. 

If you use the provided `spark` and 0.2.13 do you still get this error?

**Comment by gosha1128** [comment]
I started with a fresh Mac - Mojave 10.14.5.  Now using latest polynote(targz.) 

I followed your mac instructions ( brew, etc. ).

Now, polynote hangs right after spark-submit.  Any thoughts?

-----------------------------------------------------

[zio-default-async-8-985397764] INFO org.http4s.blaze.channel.nio1.NIO1SocketServerGroup - Service bound to address /127.0.0.1:8192
[zio-default-async-8-985397764] INFO org.http4s.server.blaze.BlazeServerBuilder - 


  _____      _                   _
 |  __ \    | |                 | |
 | |__) |__ | |_   _ _ __   ___ | |_ ___
 |  ___/ _ \| | | | | '_ \ / _ \| __/ _ \
 | |  | (_) | | |_| | | | | (_) | ||  __/
 |_|   \___/|_|\__, |_| |_|\___/ \__\___|
                __/ |
               |___/

Server running at http://127.0.0.1:8192
[zio-default-async-8-985397764] INFO org.http4s.server.blaze.BlazeServerBuilder - http4s v0.20.6 on blaze v0.14.6 started at http://127.0.0.1:8192/
[blaze-selector-1] INFO org.http4s.blaze.channel.nio1.NIO1SocketServerGroup - Accepted connection from /127.0.0.1:50799
[zio-default-async-27-985397764] INFO org.http4s.server.blaze.Http1ServerStage$$anon$1 - Unknown connection header: 'Upgrade'. Closing connection upon completion.
[blaze-selector-3] INFO org.http4s.blaze.channel.nio1.NIO1SocketServerGroup - Accepted connection from /127.0.0.1:50801
[blaze-selector-2] INFO org.http4s.blaze.channel.nio1.NIO1SocketServerGroup - Accepted connection from /127.0.0.1:50800
[blaze-selector-4] INFO org.http4s.blaze.channel.nio1.NIO1SocketServerGroup - Accepted connection from /127.0.0.1:50802
[zio-default-async-35-985397764] INFO org.http4s.server.blaze.Http1ServerStage$$anon$1 - Unknown connection header: 'Upgrade'. Closing connection upon completion.
[blaze-selector-5] INFO org.http4s.blaze.channel.nio1.NIO1SocketServerGroup - Accepted connection from /127.0.0.1:50803
[INFO]  Deploying with command:
        spark-submit --class polynote.kernel.remote.RemoteKernelClient --name "Polynote 0.2.13-SNAPSHOT session" --driver-java-options "-Dlog4j.configuration=log4j.properties -Djava.library.path=/Users/gwilliams/opt/anaconda3/lib/python3.7/site-packages/jep" --jars file:/Users/gwilliams/Packages/polynote/polynote/deps/polynote-spark-runtime.jar,file:/Users/gwilliams/Packages/polynote/polynote/deps/polynote-runtime.jar --conf spark.master=local[*] /Users/gwilliams/Packages/polynote/polynote/polynote.jar --address 192.168.92.129 --port 50804 --kernelFactory polynote.kernel.LocalSparkKernelFactory

**Comment by jonathanindig** [comment]
By hanging, do you mean that it's stuck "Waiting for remote kernel"? (3 minutes after seeing that you should get the error `java.util.concurrent.TimeoutException: Remote kernel process failed to start after 180000000000 nanoseconds` if it's indeed stuck)

If that's the case, something's probably messed up when Polynote tries to run `spark-submit`. What happens when you manually try to run
```
spark-submit --class polynote.kernel.remote.RemoteKernelClient --name "Polynote 0.2.13-SNAPSHOT session" --driver-java-options "-Dlog4j.configuration=log4j.properties -Djava.library.path=/Users/gwilliams/opt/anaconda3/lib/python3.7/site-packages/jep" --jars file:/Users/gwilliams/Packages/polynote/polynote/deps/polynote-spark-runtime.jar,file:/Users/gwilliams/Packages/polynote/polynote/deps/polynote-runtime.jar --conf spark.master=local[*] /Users/gwilliams/Packages/polynote/polynote/polynote.jar --address 192.168.92.129 --port 50804 --kernelFactory polynote.kernel.LocalSparkKernelFactory
```

**Comment by easel** [comment]
Using a scala notebook surfaces the root cause a little more easily: `java.lang.ClassCastException: cannot assign instance of org.apache.commons.lang3.time.FastDateFormat to field org.apache.spark.sql.execution.datasources.csv.CSVOptions.dateFormat of type org.apache.commons.lang3.time.FastDateFormat `

Something about polynote is forcing an incompatible version of commons lang3 onto the classpath, or something along those lines.

**Comment by akarray** [comment]
The problem still persist. I tried many versions of spark with many version of polynote till 3.11

**Comment by jonathanindig** [comment]
Hello @akarray, creating and reading a simple CSV in pyspark in Polynote seems to work for me: 

![Screen Shot 2020-09-02 at 12 18 55 PM](https://user-images.githubusercontent.com/5430417/92026938-a914d680-ed16-11ea-829b-04884c04aec0.png)

Can you please provide more details that could help me reproduce the problem? What code are you using, what does your CSV file look like? What is your environment (OS, python version, etc.) Thanks!
