### ISSUE TITLE
Can't open Polynote installed on remote AWS EC2 from my local pc 

### ISSUE THREAD

**Issue by stevesolun** [polynote/polynote#678]

**Comment by stevesolun** [comment]
I am running on Ubuntu 18.04 laptop and own an EC2 Ubuntu 18.04 machine.
I have installed Polynote there and edited the config file to listen to host 0.0.0.0 on port 8192.

For some reason I can't run Polynote.

Here is the error:

`./polynote
+ cd .
++ pip3 show jep
++ grep '^Location:'
++ cut -d : -f 2
++ cut -d ' ' -f 2
+ jep_path=/usr/local/lib/python3.7/dist-packages
++ dirname /usr/local/lib/python3.7/dist-packages
+ python_lib_path=/usr/local/lib/python3.7
++ dirname /usr/local/lib/python3.7
+ python_path=/usr/local/lib
+ test -e /usr/local/lib/libpython3.so
+ echo 'Unable to locate libpython3.so (python support probably won'\''t work)'
Unable to locate libpython3.so (python support probably won't work)
+ test -e plugins.d
+ deps=($(ls deps/*.jar))
++ ls deps/polynote-runtime.jar deps/polynote-spark-runtime.jar deps/portable-scala-reflect_2.12-0.1.0.jar deps/scala-collection-compat_2.12-2.1.1.jar deps/scala-compiler-2.12.10.jar deps/scala-library-2.12.10.jar deps/scala-reflect-2.12.10.jar deps/scala-xml_2.12-1.2.0.jar
++ IFS=:
++ echo deps/polynote-runtime.jar:deps/polynote-spark-runtime.jar:deps/portable-scala-reflect_2.12-0.1.0.jar:deps/scala-collection-compat_2.12-2.1.1.jar:deps/scala-compiler-2.12.10.jar:deps/scala-library-2.12.10.jar:deps/scala-reflect-2.12.10.jar:deps/scala-xml_2.12-1.2.0.jar
+ cp=deps/polynote-runtime.jar:deps/polynote-spark-runtime.jar:deps/portable-scala-reflect_2.12-0.1.0.jar:deps/scala-collection-compat_2.12-2.1.1.jar:deps/scala-compiler-2.12.10.jar:deps/scala-library-2.12.10.jar:deps/scala-reflect-2.12.10.jar:deps/scala-xml_2.12-1.2.0.jar
+ exec java -cp polynote.jar:deps/polynote-runtime.jar:deps/polynote-spark-runtime.jar:deps/portable-scala-reflect_2.12-0.1.0.jar:deps/scala-collection-compat_2.12-2.1.1.jar:deps/scala-compiler-2.12.10.jar:deps/scala-library-2.12.10.jar:deps/scala-reflect-2.12.10.jar:deps/scala-xml_2.12-1.2.0.jar '-Djava.library.path=/usr/local/lib/python3.7/dist-packages/jep: ' polynote.Main
[INFO]  Loading configuration from config.yml
Exception in thread "main" zio.FiberFailure: Fiber failed.
An unchecked error was produced.
io.circe.ParsingFailure: expected '<document start>', but found '<block mapping start>'
 in 'reader', line 20, column 4:
       listen:
       ^


Fiber:2 was supposed to continue to:
  a future continuation at polynote.server.Server.run(Server.scala:83)

Fiber:2 execution trace:
  at zio.ZIO.orDieWith(ZIO.scala:669)
  at scala.Predef$$anon$2.apply(Predef.scala:504)
  at polynote.config.PolynoteConfig$.load(PolynoteConfig.scala:142)
  at zio.ZIOFunctions.bracketExit(ZIO.scala:1694)
  at zio.ZIO$ZIOAutocloseableOps$.bracketAuto$extension(ZIO.scala:2585)
  at zio.ZIO$ZIOAutocloseableOps$.bracketAuto(ZIO.scala:2585)
  at zio.ZIO.run(ZIO.scala:1119)
  at zio.ZIOFunctions.fromEither(ZIO.scala:2125)
  at polynote.config.PolynoteConfig$.parseFile(PolynoteConfig.scala:116)
  at polynote.config.PolynoteConfig$.parseFile(PolynoteConfig.scala:116)
  at zio.blocking.Blocking$Service.effectBlocking(Blocking.scala:147)
  at zio.internal.FiberContext$InterruptExit$.apply(FiberContext.scala:157)
  at zio.internal.FiberContext$InterruptExit$.apply(FiberContext.scala:148)
  at zio.ZIO.ensuring(ZIO.scala:320)
  at zio.blocking.Blocking$Service.effectBlocking(Blocking.scala:123)
  at zio.blocking.Blocking$Service.effectBlocking(Blocking.scala:146)
  at zio.blocking.Blocking$Service.effectBlocking(Blocking.scala:107)
  at zio.ZIO.ensuring(ZIO.scala:318)
  at zio.internal.FiberContext$InterruptExit$.apply(FiberContext.scala:157)
  at zio.internal.FiberContext$InterruptExit$.apply(FiberContext.scala:148)
  at zio.blocking.Blocking$Service.effectBlocking(Blocking.scala:146)
  at zio.ZIO.flatten(ZIO.scala:402)
  at zio.ZIO$ZipLeftFn.apply(ZIO.scala:2665)
  at zio.UIO$.effectSuspendTotal(UIO.scala:183)
  at zio.Fiber.join(Fiber.scala:69)
  at zio.Fiber.join(Fiber.scala:69)
  at zio.internal.FiberContext.await(FiberContext.scala:619)
  at zio.blocking.Blocking$Service.effectBlocking(Blocking.scala:145)
  at zio.ZIOFunctions.effectSuspendTotal(ZIO.scala:1935)
  at polynote.config.PolynoteConfig$.parseFile(PolynoteConfig.scala:115)
  at polynote.config.PolynoteConfig$.parseFile(PolynoteConfig.scala:114)
  at zio.blocking.Blocking$Service.effectBlocking(Blocking.scala:147)
  at zio.internal.FiberContext$InterruptExit$.apply(FiberContext.scala:157)
  at zio.internal.FiberContext$InterruptExit$.apply(FiberContext.scala:148)
  at zio.ZIO.ensuring(ZIO.scala:320)
  at zio.blocking.Blocking$Service.effectBlocking(Blocking.scala:123)
  at zio.blocking.Blocking$Service.effectBlocking(Blocking.scala:146)
  at zio.blocking.Blocking$Service.effectBlocking(Blocking.scala:107)
  at zio.ZIO.ensuring(ZIO.scala:318)
  at zio.internal.FiberContext$InterruptExit$.apply(FiberContext.scala:148)
  at zio.blocking.Blocking$Service.effectBlocking(Blocking.scala:146)
  at zio.ZIO.flatten(ZIO.scala:402)
  at zio.ZIO$ZipLeftFn.apply(ZIO.scala:2665)
  at zio.UIO$.effectSuspendTotal(UIO.scala:183)
  at zio.Fiber.join(Fiber.scala:69)
  at zio.Fiber.join(Fiber.scala:69)
  at zio.internal.FiberContext.await(FiberContext.scala:619)
  at zio.blocking.Blocking$Service.effectBlocking(Blocking.scala:145)
  at zio.ZIOFunctions.effectSuspendTotal(ZIO.scala:1935)
  at polynote.config.PolynoteConfig$.parseFile(PolynoteConfig.scala:114)
  at polynote.server.Server.run(Server.scala:82)
  at zio.ZIO.ignore(ZIO.scala:509)
  at zio.blocking.Blocking$Service.effectBlocking(Blocking.scala:147)
  at zio.internal.FiberContext$InterruptExit$.apply(FiberContext.scala:157)
  at zio.internal.FiberContext$InterruptExit$.apply(FiberContext.scala:148)
  at zio.ZIO.ensuring(ZIO.scala:320)
  at zio.blocking.Blocking$Service.effectBlocking(Blocking.scala:123)
  at zio.blocking.Blocking$Service.effectBlocking(Blocking.scala:146)
  at zio.blocking.Blocking$Service.effectBlocking(Blocking.scala:107)
  at zio.ZIO.ensuring(ZIO.scala:318)
  at zio.internal.FiberContext$InterruptExit$.apply(FiberContext.scala:148)
  at zio.blocking.Blocking$Service.effectBlocking(Blocking.scala:146)
  at zio.ZIO.flatten(ZIO.scala:402)
  at zio.ZIO$ZipLeftFn.apply(ZIO.scala:2665)
  at zio.UIO$.effectSuspendTotal(UIO.scala:183)
  at zio.Fiber.join(Fiber.scala:69)
  at zio.Fiber.join(Fiber.scala:69)
  at zio.internal.FiberContext.await(FiberContext.scala:619)
  at zio.blocking.Blocking$Service.effectBlocking(Blocking.scala:145)
  at zio.ZIOFunctions.effectSuspendTotal(ZIO.scala:1935)
  at polynote.kernel.logging.Logging$Service$Default.info(Logging.scala:104)
  at polynote.kernel.logging.Logging$.info(Logging.scala:128)
  at polynote.server.Server.run(Server.scala:81)
  at zio.ZIO.orDieWith(ZIO.scala:669)
  at scala.Predef$$anon$2.apply(Predef.scala:504)
  at zio.ZIOFunctions.fromEither(ZIO.scala:2125)
  at polynote.server.Server.run(Server.scala:80)

Fiber:2 was spawned by:

Fiber:1 was supposed to continue to:
  a future continuation at polynote.app.App.main(App.scala:57)
  a future continuation at polynote.app.App.main(App.scala:56)

Fiber:1 ZIO Execution trace: <empty trace>

Fiber:1 was spawned by: <empty trace>
`

**Comment by MehdiFal** [comment]
Did you try running the python script instead of the shell one? `python polynote.py`

**Comment by dnzprmksz** [comment]
As @MehdiFal mentioned running Python script (`python polynote.py`) should work, I am running it on EMR flawlessly.

**Comment by jonathanindig** [comment]
@stevesolun your configuration was not parsed. See the log: 
```
[INFO] Loading configuration from config.yml
Exception in thread "main" zio.FiberFailure: Fiber failed.
An unchecked error was produced.
io.circe.ParsingFailure: expected '', but found ''
in 'reader', line 20, column 4:
listen:
^
```

Try pasting your config into something like http://www.yamllint.com/ and you'll see the problem. Or you can paste it here and we can help

**Comment by stevesolun** [comment]
@dnzprmksz didn't work.
![image](https://user-images.githubusercontent.com/1304538/69492365-bad56d80-0eaa-11ea-8a8a-30ca6b191bcd.png)

**Comment by stevesolun** [comment]
@jonathanindig here is my config and it did pass the yamllint site:

  

> ######### Polynote Configuration Template ##########################################################################$
> # To use, copy this template and name it `config.yml`
> #
>     cp ./config-template.yml ./config.yml
> #
> # Now, uncomment the section of the config that you'd like to change.
> #
> ####################################################################################################################$
> 
> ########## Server-level Configuration ################################
> ###
> ### These configurations are applied immediately when Polynote starts.
> ###
> ######################################################################
> 
> ###############################################################################
> # The host and port can be set by uncommenting and editing the following lines.
> ###############################################################################
> 
>    listen:
>      host: 0.0.0.0
>      port: 8192
> 
> 
> ############################################################################################
> # Storage-related configuration. Locations are all relative to Polynote's working directory.
> ############################################################################################
> 
> #storage:
> #  # The base directory Polynote should use when looking for notebooks. This location can be absolute or
> #  # relative to Polynote's working directory.
> #  dir: notebooks
> #  # These are additional mount points. Folders specified here will be 'mounted' into the base directory
> #  # and visible by their keys - so `foo: dir: bar` will show a folder `foo` in the UI that shows the contents of the
> #  # file system under `bar/`
> #  mounts:
> #    examples:
> #      dir: examples
> #    team_notebooks:
> #      dir: /shared/notebooks
> #  # The location Polynote puts various caches, such as virtual environments created for your notebooks.
> #  cache: tmp
> 
> ##########################################################
> # Configure the way Polynote runs Kernels and Interpreters
> ##########################################################
> 
> #behavior:
> #  dependency_isolation: false
> #  kernel_isolation: always
> #  shared_packages:
> #    - com.esoteric.kryo
> 
> ########## Notebook Creation Configuration #######################################################
> ###
> ### These configurations are applied to *new notebooks* only.
> ### When a *new notebook* is created, its Notebook Configuration is copied from this configuration.
> ### They do *not* affect existing notebooks.
> ###
> ###################################################################################################
> 
> ############################################################################################
> # Default repositories. Uncommenting the following lines would add four default repositories
> # which are inherited by new notebooks.
> ############################################################################################
> 
> #repositories:
> #  - ivy:
> #      base: https://my-artifacts.org/artifacts/
> #  - ivy:
> #      base: https://my-custom-ivy-repo.org/artifacts/
> #      artifact_pattern: [orgPath]/[module](_[scalaVersion])(_[sbtVersion])/[revision]/[artifact]-[revision](-[class$
> #      metadata_pattern: [orgPath]/[module](_[scalaVersion])(_[sbtVersion])/[revision]/[module](_[scalaVersion])(_[s$
> #      changing: true
> #  - maven:
> #      base: http://central.maven.org/maven2/
> #  - maven:
> #      base: http://oss.sonatype.org/content/repositories/snapshots
> #      changing: true
> 
> ############################################################################################
> # Default dependencies. Uncommenting the following lines would add some default dependencies
> # which are inherited by new notebooks.
> ############################################################################################
> 
> #dependencies:
> #  scala:
> #    - org.typelevel:cats-core_2.11:1.6.0
> #    - com.mycompany:my-library:jar:all:1.0.0
> #  python:
> #    - requests
> #    - urllib3==1.25.3
> 
> ########################################################################################
> # Default exclusions. Uncommenting the following lines would add some default exclusions
> # which are inherited by new notebooks.
> ########################################################################################
> 
> #exclusions:
> #  - com.google.guava:guava  # spark, update your guava already!!!
> 
> ########## Notebook Runtime Configuration #########################################################################
> ###
> ### These configurations are applied to *all notebooks*.
> ### When a *new notebook* is created, its Notebook Configuration is copied from this configuration.
> ###
> ### When an existing notebook is *run*, these configurations are applied at runtime. Values present in the Notebook
> ### Configuration take precedence over values here. The Notebook Configuration is *not* modified.
> ###
> ### **Note** that this means they can affect reproducibility of your notebooks when you share them with others!
> ###
> ###################################################################################################################
> 
> #################################################################################
> # Spark config params can be set by uncommenting and editing the following lines.
> #################################################################################
> 
> #spark:
> #  spark.driver.userClasspathFirst: true
> #  spark.executor.userClasspathFirst: true
> 
> ########## Front-end Configuration ################################################################################
> ###
> ### These configurations affect the behavior of the front-end. You can modify the behavior by uncommenting the
> ### following lines and editing the properties.
> ###
> ###################################################################################################################
> 
> #ui:
> #  # The URI relative to the server host where Polynote is mounted. You can edit this if mounting Polynote at a
> #  # different location behind a reverse proxy. This value is placed in the <base> tag.
> #  base_uri: /

**Comment by dnzprmksz** [comment]
@stevesolun I think you should comment Line 4 as `#    cp ./config-template.yml ./config.yml`

Also I think you should indent correctly, instead of this
```
   listen:
     host: 0.0.0.0
     port: 8192
```
you should have this
```
listen:
  host: 0.0.0.0
  port: 8192
```
Please check if that works for you.

**Comment by stevesolun** [comment]
@dnzprmksz worked like a charm, thank you so much for your detailed answer and for your time!

**Comment by dnzprmksz** [comment]
You are welcome! @stevesolun

**Comment by jonathanindig** [comment]
Glad to see this issue was resolved, thanks @dnzprmksz ! Closing.
