### ISSUE TITLE
Cannot read tfrecords using tensorflow spark connector

### ISSUE THREAD

**Issue by TaekSoonJang** [polynote/polynote#688]
**Description**
When trying to read tfrecords file by using tensorflow spark connector(https://github.com/tensorflow/ecosystem/tree/master/spark/spark-tensorflow-connector) which I built using 1.15 version, errors below popped up.

```scala
val df = spark.read.format("tfrecords").option("recordType", "Example").load("hdfs://path/to/tfrecord")
```

```
cannot assign instance of scala.collection.immutable.List$SerializationProxy to field org.apache.spark.rdd.RDD.org$apache$spark$rdd$RDD$$dependencies_ of type scala.collection.Seq in instance of org.apache.spark.rdd.MapPartitionsRDD (java.lang.ClassCastException)
```

Everything worked fine in spark-shell.

I know it's very tough to support 3rd party libraries, so I'm so glad if someone enlighten me with even small clues as to why polynote failed to do this work.

**Environment**
- Polynote Version: 
  - 0.2.13-SNAPSHOT
- Operating System: 
  - CentOS Linux release 7.6.1810 (Core)
- JVM Version:
  - 1.8.0_212
- Python Version:
  - 3.6
- How you installed Polynote: 
  - I downloaded this release https://github.com/polynote/polynote/releases/download/0.2.13/polynote-dist.tar.gz and then followed [these instructions](https://polynote.org/docs/01-installation.html).
- The command you are using to start Polynote:
  - `./polynote.py`
- Any other details that might be useful, such as whether you are running Polynote as a service, using a custom script, etc.  

**Configuration**
If applicable, please attach or paste your Polynote configuration (`config.yml`)
spark.executor.extraClassPath = /path/to/tensorflow-spark-connector.jar
spark.driver.extraClassPath = /path/to/tensorflow-spark-connector.jar
spark.master = yarn

**Notebook**
If applicable, please attach or paste the notebook file (`.ipynb`) you were trying to run when you see this bug. 

**Logs**
If applicable, please attach or paste the Polynote log
```
19/12/02 12:58:44 WARN DomainSocketFactory: The short-circuit local reads feature cannot be used because libhadoop cannot be loaded.
19/12/02 12:58:44 WARN Client: Neither spark.yarn.jars nor spark.yarn.archive is set, falling back to uploading libraries under SPARK_HOME.
19/12/02 13:07:01 WARN TaskSetManager: Lost task 64.0 in stage 0.0 (TID 6, csh62289.nhnsystem.com, executor 1): java.lang.ClassCastException: cannot assign instance of scala.collection.immutable.List$SerializationProxy to field org.apache.spark.rdd.RDD.org$apache$spark$rdd$RDD$$dependencies_ of type scala.collection.Seq in instance of org.apache.spark.rdd.MapPartitionsRDD
        at java.io.ObjectStreamClass$FieldReflector.setObjFieldValues(ObjectStreamClass.java:2133)
        at java.io.ObjectStreamClass.setObjFieldValues(ObjectStreamClass.java:1305)
        at java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:2006)
        at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:1924)
        at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:1801)
        at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1351)
        at java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:2000)
        at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:1924)
        at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:1801)
        at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1351)
        at java.io.ObjectInputStream.readObject(ObjectInputStream.java:371)
        at org.apache.spark.serializer.JavaDeserializationStream.readObject(JavaSerializer.scala:75)
        at org.apache.spark.serializer.JavaSerializerInstance.deserialize(JavaSerializer.scala:114)
        at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:83)
        at org.apache.spark.scheduler.Task.run(Task.scala:121)
        at org.apache.spark.executor.Executor$TaskRunner$$anonfun$10.apply(Executor.scala:408)
        at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:1360)
        at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:414)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)

19/12/02 13:07:01 ERROR TaskSetManager: Task 51 in stage 0.0 failed 4 times; aborting job
19/12/02 13:07:01 WARN TaskSetManager: Lost task 103.3 in stage 0.0 (TID 34, csh62289.nhnsystem.com, executor 1): TaskKilled (Stage cancelled)
19/12/02 13:07:01 WARN TaskSetManager: Lost task 55.3 in stage 0.0 (TID 37, csh62289.nhnsystem.com, executor 1): TaskKilled (Stage cancelled)
19/12/02 13:07:01 WARN TaskSetManager: Lost task 50.3 in stage 0.0 (TID 36, csh62315.nhnsystem.com, executor 2): TaskKilled (Stage cancelled)
19/12/02 13:07:01 WARN TaskSetManager: Lost task 30.3 in stage 0.0 (TID 38, csh62315.nhnsystem.com, executor 2): TaskKilled (Stage cancelled)
n19/12/02 13:15:15 WARN TaskSetManager: Lost task 9.0 in stage 1.0 (TID 40, csh62315.nhnsystem.com, executor 2): java.lang.ClassCastException: cannot assign instance of scala.collection.immutable.List$SerializationProxy to field org.apache.spark.rdd.RDD.org$apache$spark$rdd$RDD$$dependencies_ of type scala.collection.Seq in instance of org.apache.spark.rdd.MapPartitionsRDD
        at java.io.ObjectStreamClass$FieldReflector.setObjFieldValues(ObjectStreamClass.java:2133)
        at java.io.ObjectStreamClass.setObjFieldValues(ObjectStreamClass.java:1305)
        at java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:2006)
        at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:1924)
        at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:1801)
        at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1351)
        at java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:2000)
        at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:1924)
        at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:1801)
        at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1351)
        at java.io.ObjectInputStream.readObject(ObjectInputStream.java:371)
        at org.apache.spark.serializer.JavaDeserializationStream.readObject(JavaSerializer.scala:75)
        at org.apache.spark.serializer.JavaSerializerInstance.deserialize(JavaSerializer.scala:114)
        at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:83)
        at org.apache.spark.scheduler.Task.run(Task.scala:121)
        at org.apache.spark.executor.Executor$TaskRunner$$anonfun$10.apply(Executor.scala:408)
        at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:1360)
        at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:414)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
```

**Screenshots**
![image](https://user-images.githubusercontent.com/3775233/69930973-e5f23980-1508-11ea-88f5-1164ea0a4299.png)

**Additional context**

**Comment by jlloh** [comment]
Did you include the spark-tensorflow-connector maven coordinates in Configuration & dependencies > Dependencies in the notebook?

I notice this generic error appears because the spark.packages configuration isn't really passed properly to the Spark Application unless you set it through the notebook UI, and this error appears when the executors do not have the jars.

**Comment by jeremyrsmith** [comment]
@TaekSoonJang as @jlloh mentioned, is `/path/to/tensorflow-spark-connector.jar` present on all the executors? It would be better to add this JAR as a dependency with its maven coordinates in the notebook configuration, as then the executors will be able to download it as well.

Going to close this issue, please reopen if it still fails when you add the library as a dependency.

**Comment by TaekSoonJang** [comment]
@jlloh @jeremyrsmith Thanks for the solution!
