### ISSUE TITLE
Misleading error message when `--config` flag value is missing

### ISSUE THREAD

**Issue by iorch** [polynote/polynote#745]
I followed the instruction to run it on docker, created the `config.ym`l and the `notebooks` directory, but wasn't able to run it properly.

```
$ docker run --rm -it -p 127.0.0.1:8192:8192 -p 127.0.0.1:4040-4050:4040-4050 -v `pwd`/config.yml:/opt/config/config.yml -v `pwd`/notebooks:/opt/notebooks/ polynote/polynote:latest --config 
java -cp polynote.jar:polynote.jar:/opt/polynote/deps/scala-library-2.11.12.jar:/opt/polynote/deps/polynote-runtime.jar:/opt/polynote/deps/scala-reflect-2.11.12.jar:/opt/polynote/deps/polynote-spark-runtime.jar:/opt/polynote/deps/portable-scala-reflect_2.11-0.1.0.jar:/opt/polynote/deps/scala-collection-compat_2.11-2.1.1.jar:/opt/polynote/deps/scala-xml_2.11-1.2.0.jar:/opt/polynote/deps/scala-compiler-2.11.12.jar -Djava.library.path=/usr/local/lib/python3.7/dist-packages/jep polynote.Main --config
Exception in thread "main" zio.FiberFailure: Fiber failed.
An unchecked error was produced.
java.lang.IllegalArgumentException: Unknown argument --config
	at polynote.server.Server$.polynote$server$Server$$parseArgs(Server.scala:205)
	at polynote.server.Server$$anonfun$run$1.apply(Server.scala:86)
	at polynote.server.Server$$anonfun$run$1.apply(Server.scala:86)
	at zio.internal.FiberContext.evaluateNow(FiberContext.scala:280)
	at zio.internal.FiberContext.zio$internal$FiberContext$$run$body$1(FiberContext.scala:596)
	at zio.internal.FiberContext$$anonfun$6.run(FiberContext.scala:596)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

Fiber:2 was supposed to continue to:
  a future continuation at polynote.server.Server$$anonfun$run$2.apply(Server.scala:86)

Fiber:2 execution trace:
  at zio.ZIO$$anonfun$orDieWith$1.apply(ZIO.scala:669)
  at scala.Predef$$anon$1.apply(Predef.scala:389)
  at zio.ZIOFunctions$$anonfun$fromEither$1.apply(ZIO.scala:2125)
  at polynote.server.Server$$anonfun$run$1.apply(Server.scala:86)

Fiber:2 was spawned by:

Fiber:1 was supposed to continue to:
  a future continuation at polynote.app.App$$anonfun$main$1$$anonfun$apply$3.apply(App.scala:56)
  a future continuation at polynote.app.App$$anonfun$main$1.apply(App.scala:56)

Fiber:1 ZIO Execution trace: <empty trace>

Fiber:1 was spawned by: <empty trace>
```

**Comment by jonathanindig** [comment]
Hi @iorch, it looks like the error message is a bit confusing if you don't specify a config file with that  flag - you need to do something like `--config /path/to/config.yml`. For example (from [here](https://github.com/polynote/polynote/tree/master/docker#usage-instructions)): 

```
docker run --rm -it -p 127.0.0.1:8192:8192 -p 127.0.0.1:4040-4050:4040-4050 -v `pwd`/config.yml:/opt/config/config.yml -v `pwd`/notebooks:/opt/notebooks/ polynote/polynote:latest --config /opt/config/config.yml
```

We'll try to fix that error message though!
