### ISSUE TITLE
Scala 2.12 + Spark 2.4.4 + hadoop 2.9.2 do not work

### ISSUE THREAD

**Issue by antonkulaga** [polynote/polynote#753]
I failed to make polynote work with Scala 2.12 and Spark 2.4.4 ( my current docker container is https://github.com/antonkulaga/polynote ). Probably the classpath issue, as it cannot find org.apache libraries. Strangly the same stuff used to work for me for 2.11.x
![polynote_issue](https://user-images.githubusercontent.com/842436/72658414-41915d00-39b9-11ea-93f7-9b5d75f57587.png)

**Comment by antonkulaga** [comment]
I noticed that in the official polynote container you use 2.11 version of spark 2.4.4 despite marking it with scala2.12spark2.4.4 tag
```
RUN wget -q https://www-us.apache.org/dist/spark/spark-2.4.4/spark-2.4.4-bin-hadoop2.7.tgz && \
    tar xfz spark-2.4.4-bin-hadoop2.7.tgz && \
    rm spark-2.4.4-bin-hadoop2.7.tgz
```

Scala 2.12 is default only for spark 2.4.2,but they returned to 2.11 later according to https://spark.apache.org/downloads.html

**Comment by antonkulaga** [comment]
Managed to make it work with my container, but had a lot of frustration on my way :(
One of the main confusion sources is that if master is not configured it often omits including spark dependencies without notifying the user

**Comment by jonathanindig** [comment]
Thanks for the catch! We'll look into updating our docker distribution.

**Comment by milenkovicm** [comment]
I guess error I'm getting with `polynote/polynote:0.2.17-2.12-spark2.4` may be relevant

```
20/02/01 16:11:22 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java cl                                                asses where applicable
Exception in thread "main" java.lang.BootstrapMethodError: java.lang.NoClassDefFoundError: scala/runtime/java8/JFunction                                                0$mcZ$sp
        at zio.scheduler.internal$$anon$1.<init>(SchedulerLive.scala:32)
        at zio.scheduler.internal$.<init>(SchedulerLive.scala:27)
        at zio.scheduler.internal$.<clinit>(SchedulerLive.scala)
        at zio.scheduler.SchedulerLive$$anon$3.<init>(SchedulerLive.scala:70)
        at zio.scheduler.SchedulerLive.$init$(SchedulerLive.scala:69)
        at polynote.app.App$$anon$1.<init>(App.scala:19)
        at polynote.app.App.$init$(App.scala:19)
        at polynote.kernel.remote.RemoteKernelClient$.<init>(RemoteKernel.scala:262)
        at polynote.kernel.remote.RemoteKernelClient$.<clinit>(RemoteKernel.scala)
        at polynote.kernel.remote.RemoteKernelClient.main(RemoteKernel.scala)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.apache.spark.deploy.JavaMainApplication.start(SparkApplication.scala:52)
        at org.apache.spark.deploy.SparkSubmit.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:845)                                                              at org.apache.spark.deploy.SparkSubmit.doRunMain$1(SparkSubmit.scala:161)
        at org.apache.spark.deploy.SparkSubmit.submit(SparkSubmit.scala:184)
        at org.apache.spark.deploy.SparkSubmit.doSubmit(SparkSubmit.scala:86)
        at org.apache.spark.deploy.SparkSubmit$$anon$2.doSubmit(SparkSubmit.scala:920)
        at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:929)
        at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
Caused by: java.lang.NoClassDefFoundError: scala/runtime/java8/JFunction0$mcZ$sp
        ... 22 more
Caused by: java.lang.ClassNotFoundException: scala.runtime.java8.JFunction0$mcZ$sp
        at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
        ... 22 more
```
easy to reproduce, just fetch docker and run `Scala Spark to Pandas` notebook.

**Comment by jeremyrsmith** [comment]
I think I've figured this out... it looks like zio for Scala 2.12 has a dependency on scala-java8-compat which we're not adding to our `deps` during the packaging.

**Comment by Igor-mr** [comment]
Hi, I've got same issue but with Scala 2.11

![Screenshot 2020-12-04 at 12 28 09](https://user-images.githubusercontent.com/21989531/101148783-1c3c2a80-362f-11eb-9c8d-c367aed7057a.png)
![Screenshot 2020-12-04 at 12 39 10](https://user-images.githubusercontent.com/21989531/101148886-3bd35300-362f-11eb-9fa9-d2e1f284751c.png)
