### ISSUE TITLE
failed to start Python interpreter

### ISSUE THREAD

**Issue by conderls** [polynote/polynote#936]
**Description**
after starting polynote with `./polynote.py`, it failed to starting python interpreter with `KernelError: 
java.io.IOException: Connection reset by peer`.  While it can successfully run scala code in same session.

**Environment**
- Polynote Version: 
   - 0.3.11
- Operating System: 
  - Mac OS Catalina 10.15.5
- JVM Version:
  - 1.8.0_212
- Python Version:
  - 3.7.4
- How you installed Polynote: 
  I downloaded this release https://github.com/polynote/polynote/releases/download/0.3.11/polynote-dist.tar.gz and then followed [these instructions](https://polynote.org/docs/01-installation.html).
- The command you are using to start Polynote:
  - `./polynote.py`

**Configuration**
No, not even copy config-template.yml as config.yml

**Screenshots**
![image](https://user-images.githubusercontent.com/6688515/87866182-165fe880-c9b1-11ea-9e50-cfb2e46e3bca.png)

Error while running python code
![image](https://user-images.githubusercontent.com/6688515/87866193-3f807900-c9b1-11ea-9763-ac050122218b.png)

**Comment by jonathanindig** [comment]
Hi @conderls, this error message means that the kernel (a separate process) probably died for some other reason. 

Are there any errors from stdout/stderr from the polynote process that might provide some more information about what's happening? 

Have you installed Polynote's Python dependencies?

**Comment by conderls** [comment]
The python(3.7.4) dependencies:
```
Name: jep
Version: 3.9.0
--
Name: jedi
Version: 0.15.1
--
Name: pyspark
Version: 2.4.4
--
Name: virtualenv
Version: 16.7.7
```

check [here](https://gist.github.com/conderls/9053f9b7c91a7e15c90bbd420b1ecf8b) for full stdout/stderr log.

**Comment by jonathanindig** [comment]
So the most obvious thing I see here: 

```        |   java.net.BindException: Address already in use
        |   	at sun.nio.ch.Net.bind0(Native Method)
        |   	at sun.nio.ch.Net.bind(Net.java:433)
        |   	at sun.nio.ch.Net.bind(Net.java:425)
        |   	at sun.nio.ch.ServerSocketChannelImpl.bind(ServerSocketChannelImpl.java:223)
        |   	at uzhttp.server.Server$$anonfun$uzhttp$server$Server$$mkSocket$3$$anonfun$apply$99.apply(Server.scala:621)
        |   	at uzhttp.server.Server$$anonfun$uzhttp$server$Server$$mkSocket$3$$anonfun$apply$99.apply(Server.scala:621)
        |   	at zio.internal.FiberContext.evaluateNow(FiberContext.scala:458)
        |   	at zio.internal.FiberContext.zio$internal$FiberContext$$run$body$2(FiberContext.scala:687)
        |   	at zio.internal.FiberContext$$anonfun$12.run(FiberContext.scala:687)
        |   	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        |   	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        |   	at java.lang.Thread.run(Thread.java:748)```

Do you have anything running on port 8192? Maybe another instance of Polynote?

This exception shouldn't be related to the kernel error though...

**Comment by conderls** [comment]
No, I checked the port 8192 status by `lsof -i:8192` before running polynote.

**Comment by jonathanindig** [comment]
Hi @conderls so this time I see it ran Python code successfully (aside from the import error). Are you still running into the original issue or has that been resolved?

I haven't really tested running Polynote itself inside of a virutalenv - Polynote creates its own virtualenv for each notebook if it has Python dependencies so I'm not sure how it would interact with the other virtualenv you created (probably would just ignore it which would explain why you see that it seems to install dependencies each time). 

So now the problem is that you specified `bokeh` as a dependency in your notebook configuration, it installs bokeh successfully but the notebook itself still shows this error? I'm not quite sure what the problem would be there. Do you get a similar error with other dependencies? It looks like numpy is working for you for example.

**Comment by conderls** [comment]
Hi @jonathanindig, Actually, I still failed to run python code, then I created a brand new env to run polynote:

## create new python env:
```bash
conda create -n pn python=3.7 pip numpy matplotlib pandas pyarrow bokeh
conda activate pn
pip install jep jedi
```
the version of pkgs as following, with `jep==3.9.0 and jedi==0.17.2`:
![image](https://user-images.githubusercontent.com/6688515/88613027-26697d80-d0bf-11ea-96f7-3ebcd649c54d.png)

## run polynote
1. run polynote with `./polynote.py`
### error related to `@rpath/libpython3.7m.dylib`
during the first try, one exception raised:
**Uncaught exception:** /Users/conderls/Programs/anaconda3/envs/pn/lib/python3.7/site-packages/jep/libjep.jnilib: dlopen(/Users/conderls/Programs/anaconda3/envs/pn/lib/python3.7/site-packages/jep/libjep.jnilib, 1): Library not loaded: @rpath/libpython3.7m.dylib Referenced from: /Users/conderls/Programs/anaconda3/envs/pn/lib/python3.7/site-packages/jep/libjep.jnilib Reason: image not found (java.lang.UnsatisfiedLinkError)

**solution**: install_name_tool -add_rpath $DATA/usr/anaconda3/envs/pn/lib  \$DATA/anaconda3/envs/pn/lib/python3.7/site-packages/jep/libjep.jnilib

### check port:8192 availability
check by `lsof -i:8192`, kill process leasening to port:8192 to make sure it is available.

### rerun
port:8192 is available, rerun the code. `java.net.BindException: Address already in use` shows again.

**Comment by jonathanindig** [comment]
Sorry @conderls, I'm not quite sure what the problem might be other than something else running on that port. This doesn't seem to happen every time you try to run Polynote, since it seems that at least sometimes you are able to access the server, right? So how often do you see this BindException and does it correlate with anything else?

**Comment by jonathanindig** [comment]
Hi @conderls are you still running into this issue?

**Comment by joseph-long** [comment]
I encountered the same issue as OP, found a running process that I had to kill and restart polynote to free the port. Then I encountered the next issue with the UnsatisfiedLinkError, and used `install_name_tool` to fix it. Currently I attempt to run `print('hi')` in a Python cell and get:

```
KernelError

java.io.IOException: Broken pipe

Uncaught exception: Broken pipe (java.io.IOException)

    sun.nio.ch.FileDispatcherImpl.write0(FileDispatcherImpl.java:-2)
    sun.nio.ch.SocketDispatcher.write(SocketDispatcher.java:62)
    sun.nio.ch.IOUtil.writeFromNativeBuffer(IOUtil.java:113)
    sun.nio.ch.IOUtil.write(IOUtil.java:79)
    sun.nio.ch.IOUtil.write(IOUtil.java:50)
    sun.nio.ch.SocketChannelImpl.write(SocketChannelImpl.java:484)
    polynote.kernel.remote.SocketTransport$FramedSocket.writeSize(transport.scala:462)
    polynote.kernel.remote.SocketTransport$FramedSocket.$anonfun$sendKeepalive$9(transport.scala:469)
    scala.runtime.java8.JFunction0$mcI$sp.apply(JFunction0$mcI$sp.java:23)
    zio.internal.FiberContext.evaluateNow(FiberContext.scala:458)
    zio.internal.FiberContext.$anonfun$evaluateLater$1(FiberContext.scala:687)
    java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
    java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
    java.lang.Thread.run(Thread.java:832)
```

One commonality is that we both seem to be using `conda`, which does mess with rpaths and similar itself... but maybe installing jep with pip doesn't get those changes written into the lib?

**Comment by stevemarin** [comment]
@joseph-long might have it right.  I was struggling to get Polynote to initialize a Python kernel.  I ultimately found creating a Conda environment and installing packages via pip works fine.  Installing the exact same packages via conda from the conda-forge channel causes the issue reproduced below.

To make the conda environment that had packages installed with conda, work I conda uninstalled openjdk (openjdk  8.0.265  h516909a_0) which also uninstalled jep.  I then pip installed jep and it worked fine.  Note sure what that means, but it seemed to be a potentially useful data point!  Thanks!

```
[REMOTE | piaenfpanefpaef.ipynb]
        |   ImportError: numpy.core.multiarray failed to import
        |   ImportError: numpy.core.multiarray failed to import
        |   ImportError: numpy.core.multiarray failed to import
        |   ImportError: numpy.core.multiarray failed to import
        |   ImportError: numpy.core.multiarray failed to import
        |   ImportError: numpy.core.multiarray failed to import
        |   ImportError: numpy.core.multiarray failed to import
        |   ImportError: numpy.core.multiarray failed to import
        |   ImportError: numpy.core.multiarray failed to import
        |   ImportError: numpy.core.multiarray failed to import
        |   ImportError: numpy.core.multiarray failed to import
        |   ERROR:root:code for hash md5 was not found.
        |   Traceback (most recent call last):
        |     File "/home/steve/dev/polynote/conda-env-38-ver2/lib/python3.8/hashlib.py", line 251, in <module>
        |       globals()[__func_name] = __get_hash(__func_name)
        |     File "/home/steve/dev/polynote/conda-env-38-ver2/lib/python3.8/hashlib.py", line 120, in __get_builtin_constructor
        |       raise ValueError('unsupported hash type ' + name)
        |   ValueError: unsupported hash type md5
        |   ERROR:root:code for hash sha1 was not found.
        |   Traceback (most recent call last):
        |     File "/home/steve/dev/polynote/conda-env-38-ver2/lib/python3.8/hashlib.py", line 251, in <module>
        |       globals()[__func_name] = __get_hash(__func_name)
        |     File "/home/steve/dev/polynote/conda-env-38-ver2/lib/python3.8/hashlib.py", line 120, in __get_builtin_constructor
        |       raise ValueError('unsupported hash type ' + name)
        |   ValueError: unsupported hash type sha1
        |   ERROR:root:code for hash sha224 was not found.
        |   Traceback (most recent call last):
        |     File "/home/steve/dev/polynote/conda-env-38-ver2/lib/python3.8/hashlib.py", line 251, in <module>
        |       globals()[__func_name] = __get_hash(__func_name)
        |     File "/home/steve/dev/polynote/conda-env-38-ver2/lib/python3.8/hashlib.py", line 120, in __get_builtin_constructor
        |       raise ValueError('unsupported hash type ' + name)
        |   ValueError: unsupported hash type sha224
        |   ERROR:root:code for hash sha256 was not found.
        |   Traceback (most recent call last):
        |     File "/home/steve/dev/polynote/conda-env-38-ver2/lib/python3.8/hashlib.py", line 251, in <module>
        |       globals()[__func_name] = __get_hash(__func_name)
        |     File "/home/steve/dev/polynote/conda-env-38-ver2/lib/python3.8/hashlib.py", line 120, in __get_builtin_constructor
        |       raise ValueError('unsupported hash type ' + name)
        |   ValueError: unsupported hash type sha256
        |   ERROR:root:code for hash sha384 was not found.
        |   Traceback (most recent call last):
        |     File "/home/steve/dev/polynote/conda-env-38-ver2/lib/python3.8/hashlib.py", line 251, in <module>
        |       globals()[__func_name] = __get_hash(__func_name)
        |     File "/home/steve/dev/polynote/conda-env-38-ver2/lib/python3.8/hashlib.py", line 120, in __get_builtin_constructor
        |       raise ValueError('unsupported hash type ' + name)
        |   ValueError: unsupported hash type sha384
        |   ERROR:root:code for hash sha512 was not found.
        |   Traceback (most recent call last):
        |     File "/home/steve/dev/polynote/conda-env-38-ver2/lib/python3.8/hashlib.py", line 251, in <module>
        |       globals()[__func_name] = __get_hash(__func_name)
        |     File "/home/steve/dev/polynote/conda-env-38-ver2/lib/python3.8/hashlib.py", line 120, in __get_builtin_constructor
        |       raise ValueError('unsupported hash type ' + name)
        |   ValueError: unsupported hash type sha512
        |   ERROR:root:code for hash blake2b was not found.
        |   Traceback (most recent call last):
        |     File "/home/steve/dev/polynote/conda-env-38-ver2/lib/python3.8/hashlib.py", line 251, in <module>
        |       globals()[__func_name] = __get_hash(__func_name)
        |     File "/home/steve/dev/polynote/conda-env-38-ver2/lib/python3.8/hashlib.py", line 120, in __get_builtin_constructor
        |       raise ValueError('unsupported hash type ' + name)
        |   ValueError: unsupported hash type blake2b
        |   ERROR:root:code for hash blake2s was not found.
        |   Traceback (most recent call last):
        |     File "/home/steve/dev/polynote/conda-env-38-ver2/lib/python3.8/hashlib.py", line 251, in <module>
        |       globals()[__func_name] = __get_hash(__func_name)
        |     File "/home/steve/dev/polynote/conda-env-38-ver2/lib/python3.8/hashlib.py", line 120, in __get_builtin_constructor
        |       raise ValueError('unsupported hash type ' + name)
        |   ValueError: unsupported hash type blake2s
        |   ERROR:root:code for hash sha3_224 was not found.
        |   Traceback (most recent call last):
        |     File "/home/steve/dev/polynote/conda-env-38-ver2/lib/python3.8/hashlib.py", line 251, in <module>
        |       globals()[__func_name] = __get_hash(__func_name)
        |     File "/home/steve/dev/polynote/conda-env-38-ver2/lib/python3.8/hashlib.py", line 120, in __get_builtin_constructor
        |       raise ValueError('unsupported hash type ' + name)
        |   ValueError: unsupported hash type sha3_224
        |   ERROR:root:code for hash sha3_256 was not found.
        |   Traceback (most recent call last):
        |     File "/home/steve/dev/polynote/conda-env-38-ver2/lib/python3.8/hashlib.py", line 251, in <module>
        |       globals()[__func_name] = __get_hash(__func_name)
        |     File "/home/steve/dev/polynote/conda-env-38-ver2/lib/python3.8/hashlib.py", line 120, in __get_builtin_constructor
        |       raise ValueError('unsupported hash type ' + name)
        |   ValueError: unsupported hash type sha3_256
        |   ERROR:root:code for hash sha3_384 was not found.
        |   Traceback (most recent call last):
        |     File "/home/steve/dev/polynote/conda-env-38-ver2/lib/python3.8/hashlib.py", line 251, in <module>
        |       globals()[__func_name] = __get_hash(__func_name)
        |     File "/home/steve/dev/polynote/conda-env-38-ver2/lib/python3.8/hashlib.py", line 120, in __get_builtin_constructor
        |       raise ValueError('unsupported hash type ' + name)
        |   ValueError: unsupported hash type sha3_384
        |   ERROR:root:code for hash sha3_512 was not found.
        |   Traceback (most recent call last):
        |     File "/home/steve/dev/polynote/conda-env-38-ver2/lib/python3.8/hashlib.py", line 251, in <module>
        |       globals()[__func_name] = __get_hash(__func_name)
        |     File "/home/steve/dev/polynote/conda-env-38-ver2/lib/python3.8/hashlib.py", line 120, in __get_builtin_constructor
        |       raise ValueError('unsupported hash type ' + name)
        |   ValueError: unsupported hash type sha3_512
        |   ERROR:root:code for hash shake_128 was not found.
        |   Traceback (most recent call last):
        |     File "/home/steve/dev/polynote/conda-env-38-ver2/lib/python3.8/hashlib.py", line 251, in <module>
        |       globals()[__func_name] = __get_hash(__func_name)
        |     File "/home/steve/dev/polynote/conda-env-38-ver2/lib/python3.8/hashlib.py", line 120, in __get_builtin_constructor
        |       raise ValueError('unsupported hash type ' + name)
        |   ValueError: unsupported hash type shake_128
        |   ERROR:root:code for hash shake_256 was not found.
        |   Traceback (most recent call last):
        |     File "/home/steve/dev/polynote/conda-env-38-ver2/lib/python3.8/hashlib.py", line 251, in <module>
        |       globals()[__func_name] = __get_hash(__func_name)
        |     File "/home/steve/dev/polynote/conda-env-38-ver2/lib/python3.8/hashlib.py", line 120, in __get_builtin_constructor
        |       raise ValueError('unsupported hash type ' + name)
        |   ValueError: unsupported hash type shake_256
        |   An error occurred while initializing the Python interpreter. /home/steve/dev/polynote/conda-env-38-ver2/lib/python3.8/lib-dynload/_struct.cpython-38-x86_64-linux-gnu.so: undefined symbol: _PyFloat_Pack4
        |   Traceback (most recent call last):
        |     File "/home/steve/dev/polynote/conda-env-38-ver2/lib/python3.8/site-packages/parso/cache.py", line 13, in <module>
        |       import cPickle as pickle
        |   ModuleNotFoundError: No module named 'cPickle'
        |   During handling of the above exception, another exception occurred:
        |   Traceback (most recent call last):
        |     File "<string>", line 6, in <module>
        |     File "/home/steve/dev/polynote/conda-env-38-ver2/lib/python3.8/site-packages/jedi/__init__.py", line 32, in <module>
        |       from jedi.api import Script, Interpreter, set_debug_function, \
        |     File "/home/steve/dev/polynote/conda-env-38-ver2/lib/python3.8/site-packages/jedi/api/__init__.py", line 15, in <module>
        |       import parso
        |     File "/home/steve/dev/polynote/conda-env-38-ver2/lib/python3.8/site-packages/parso/__init__.py", line 42, in <module>
        |       from parso.grammar import Grammar, load_grammar
        |     File "/home/steve/dev/polynote/conda-env-38-ver2/lib/python3.8/site-packages/parso/grammar.py", line 10, in <module>
        |       from parso.cache import parser_cache, load_module, try_to_save_module
        |     File "/home/steve/dev/polynote/conda-env-38-ver2/lib/python3.8/site-packages/parso/cache.py", line 15, in <module>
        |       import pickle
        |     File "/home/steve/dev/polynote/conda-env-38-ver2/lib/python3.8/pickle.py", line 33, in <module>
        |       from struct import pack, unpack
        |     File "/home/steve/dev/polynote/conda-env-38-ver2/lib/python3.8/struct.py", line 13, in <module>
        |       from _struct import *
        |   ImportError: /home/steve/dev/polynote/conda-env-38-ver2/lib/python3.8/lib-dynload/_struct.cpython-38-x86_64-linux-gnu.so: undefined symbol: _PyFloat_Pack4
```
